export const tasinmazNiteligiOptions = [
  "AKARYAKIT TESİSİ (BENZİNLİK, LPG, DOLUM VB.)",
  "ARSA",
  "AVM (KOMPLE ALIŞVERİŞ MERKEZİ)",
  "BÜRO (OFİSLER, DAİRE TİPİ İŞYERLERİ VB.)",
  "DEPO (SOĞUK HAVA DEPOSU, ANTREPO, LOJİSTİK DEPO VB.)",
  "DÜKKAN (MAĞAZALAR, ESNAF İŞYERLERİ, PERAKENDE ALIŞVERİŞ YERLERİ VB.)",
  "EĞİTİM TESİSİ (DERSHANE, ÖZEL OKUL, ÜNİVERSİTE VB.)",
  "EĞLENCE TESİSİ (SİNEMA, TİYATRO, LUNAPARK, OYUNALANI VB.)",
  "KONUT (APARTMAN DAİRESİ, VİLLA, GECEKONDU, MESKEN, ÜÇ KATA KADAR HER TÜRLÜ KONUT)",
  "KÜÇÜK SANAYİ TESİSİ (OTO TAMİRHANE, TEKSTİL ATÖLYELERİ, İMALATHANELER VB.)",
  "KÜÇÜK TURİSTİK TESİS (PANSİYON, ÇADIR KAMPI VB.)",
  "MENKUL DEĞERLEME (MAKİNA, GEMİ, TİCARİ PLAKA, MARKA VB.)",
  "SAĞLIK TESİSİ (HASTANE, POLİKLİNİK, TANI MERKEZİ VB.)",
  "SANAYİ TESİSİ (HER TÜRLÜ FABRİKA, AĞIR SANAYİ TESİSİ VB.)",
  "SERA",
  "SPOR TESİSİ / SOSYAL TESİS",
  "TARIM/HAYVANCILIK TESİSİ (TAVUK ÇİFTLİĞİ, BESİHANE VB.)",
  "TARLA, BAĞ, BAHÇE VB.",
  "TERSHANE/LİMAN VB.",
  "TİCARİ BİNA (PLAZA, İŞMERKEZİ, İŞHANI, OTO PLAZA VB.)",
  "TURİSTİK TESİS (OTEL, MOTEL, TATİL KÖYÜ VB.)",
  "RAFİNERİ, AKARYAKIT DEPOLAMA TESİSLERİ, DİĞER ENERJİ TESİSLERİ",
] as const;

export const bankalarOptions = [
  "Akbank T.A.Ş.",
  "Alternatifbank A.Ş.",
  "Anadolubank A.Ş.",
  "Arap Türk Bankası A.Ş.",
  "Bank Mellat",
  "Bank of China Turkey A.Ş.",
  "Burgan Bank A.Ş.",
  "Citibank A.Ş.",
  "Colendi Bank A.Ş.",
  "DenizBank A.Ş.",
  "Deutsche Bank A.Ş.",
  "Enpara Bank A.Ş.",
  "Fibabanka A.Ş.",
  "FUPS Bank A.Ş.",
  "HSBC Bank A.Ş.",
  "ICBC Turkey Bank A.Ş.",
  "ING Bank A.Ş.",
  "Intesa Sanpaolo S.p.A.",
  "JPMorgan Chase Bank N.A.",
  "MUFG Bank Turkey A.Ş.",
  "Odeabank A.Ş.",
  "QNB Bank A.Ş.",
  "Rabobank A.Ş.",
  "Société Générale",
  "Şekerbank T.A.Ş.",
  "T.C. Ziraat Bankası A.Ş.",
  "Turkish Bank A.Ş.",
  "Turkland Bank A.Ş.",
  "Türk Ekonomi Bankası A.Ş.",
  "Türk Ticaret Bankası A.Ş.",
  "Türkiye Garanti Bankası A.Ş.",
  "Türkiye Halk Bankası A.Ş.",
  "Türkiye İş Bankası A.Ş.",
  "Türkiye Vakıflar Bankası T.A.O.",
  "Yapı ve Kredi Bankası A.Ş.",
  "Ziraat Dinamik Banka A.Ş.",
  "Adil Katılım Bankası A.Ş.",
  "Albaraka Türk Katılım Bankası A.Ş.",
  "Dünya Katılım Bankası A.Ş.",
  "Hayat Finans Katılım Bankası A.Ş.",
  "Kuveyt Türk Katılım Bankası A.Ş.",
  "T.O.M. Katılım Bankası A.Ş.",
  "Türkiye Emlak Katılım Bankası A.Ş.",
  "Türkiye Finans Katılım Bankası A.Ş.",
  "Vakıf Katılım Bankası A.Ş.",
  "Ziraat Katılım Bankası A.Ş.",
  "Aktif Yatırım Bankası A.Ş.",
  "A&T Bank A.Ş.",
  "Bankpozitif Kredi ve Kalkınma Bankası A.Ş.",
  "D Yatırım Bankası A.Ş.",
  "Destek Yatırım Bankası A.Ş.",
  "Diler Yatırım Bankası A.Ş.",
  "Golden Global Yatırım Bankası A.Ş.",
  "GSD Yatırım Bankası A.Ş.",
  "Hedef Yatırım Bankası A.Ş.",
  "İstanbul Takas ve Saklama Bankası A.Ş.",
  "Misyon Yatırım Bankası A.Ş.",
  "Nurol Yatırım Bankası A.Ş.",
  "Pasha Yatırım Bankası A.Ş.",
  "Q Yatırım Bankası A.Ş.",
  "Tera Yatırım Bankası A.Ş.",
  "Türkiye İhracat Kredi Bankası A.Ş. (Türk Eximbank)",
  "Türkiye Kalkınma ve Yatırım Bankası A.Ş.",
  "Türkiye Sınai Kalkınma Bankası A.Ş.",
  "Birleşik Fon Bankası A.Ş.",
] as const;

export const tasarrufFinansmanKuruluslariOptions = [
  "Adil Tasarruf Finansman A.Ş.",
  "Albayrak Tasarruf Finansman A.Ş.",
  "Birevim Tasarruf Finansman A.Ş.",
  "Emin Evim Tasarruf Finansman A.Ş.",
  "Emlak Katılım Tasarruf Finansman A.Ş.",
  "Fuzul Tasarruf Finansman A.Ş.",
  "İmece Tasarruf Finansman A.Ş.",
  "Katılımevim Tasarruf Finansman A.Ş.",
  "Sinpaş Tasarruf Finansman A.Ş.",
] as const;

export const degerlemeKurumBankaGroups = [
  { label: "Bankalar", options: bankalarOptions },
  { label: "Tasarruf Finansman Kuruluşları", options: tasarrufFinansmanKuruluslariOptions },
] as const;

// Aynı sırada: BANKALAR + KATILIM BANKALARI + KALKINMA VE YATIRIM BANKALARI (bankalarOptions ile birebir eşleşir).
const bankalarKisaltma = [
  "AKBNK",
  "ALTBK",
  "ANDBK",
  "ATB",
  "BMELLAT",
  "BOCT",
  "BURGAN",
  "CITI",
  "COLENDI",
  "DENIZ",
  "DEUTSCHE",
  "ENPARA",
  "FIBA",
  "FUPS",
  "HSBC",
  "ICBC",
  "ING",
  "INTESA",
  "JPM",
  "MUFG",
  "ODEA",
  "QNB",
  "RABO",
  "SOCGEN",
  "SEKER",
  "ZIRAAT",
  "TURKBANK",
  "T-BANK",
  "TEB",
  "TURKTB",
  "GARANTI",
  "HALKBANK",
  "ISBANK",
  "VAKIF",
  "YKB",
  "ZDINAMIK",
  "ADILKAT",
  "ALBARAKA",
  "DUNYAKAT",
  "HAYATFIN",
  "KUVEYTTK",
  "TOMKAT",
  "EMLAKKAT",
  "TFKB",
  "VAKIFKAT",
  "ZIRAATKAT",
  "AKTIF",
  "ATBANK",
  "BANKPOZ",
  "DYATIRIM",
  "DESTEKYB",
  "DILER",
  "GOLDENG",
  "GSD",
  "HEDEFYB",
  "TAKASBANK",
  "MISYON",
  "NUROL",
  "PASHA",
  "QYATIRIM",
  "TERA",
  "EXIMBANK",
  "TKYB",
  "TSKB",
  "BFB",
] as const;

const tasarrufFinansmanKisaltma = [
  "ADILTFS",
  "ALBAYRAKTF",
  "BIREVIM",
  "EMINEVIM",
  "EMLAKTF",
  "FUZUL",
  "IMECE",
  "KATILIMEVIM",
  "SINPAS",
] as const;

export const kurumBankaKisaltmaMap: Record<string, string> = Object.fromEntries([
  ...bankalarOptions.map((name, i) => [name, bankalarKisaltma[i]]),
  ...tasarrufFinansmanKuruluslariOptions.map((name, i) => [name, tasarrufFinansmanKisaltma[i]]),
]);

export function getKurumKisaltma(kurumAdi: string): string {
  return kurumBankaKisaltmaMap[kurumAdi] ?? "GENEL";
}

export const degerlemeFirmasiOptions = [
  "1A Grup Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "24 Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "4A Danışmanlık ve Gayrimenkul Değerleme A.Ş.",
  "A Gayrimenkul Değerleme A.Ş.",
  "ABAK Gayrimenkul Değerleme ve Müşavirlik A.Ş.",
  "ACAR Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "ACE Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "AÇI Kurumsal Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "ADEN Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "ADİL Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "ADMER Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "AGD Anadolu Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Akademi Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Aktif Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Alan Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "Alesta Kurumsal Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Alfa Anadolu Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "Analiz Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "Anayapı Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Angora Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "Anka Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Anreva Kurumsal Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Archi Danışmanlık ve Gayrimenkul Değerleme A.Ş.",
  "Area Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Arge Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Ari Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Arıkan Taşınmaz Değerleme A.Ş.",
  "Arma Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "Artı Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Arves Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Asal Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Atak Gayrimenkul Değerleme A.Ş.",
  "Atlas Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Avrupa Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Başkent Taşınmaz Değerleme A.Ş.",
  "Bilge Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Bilgi Gayrimenkul Değerleme A.Ş.",
  "CLS Kurumsal Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Çınar Taşınmaz Değerleme ve Müşavirlik A.Ş.",
  "Çizgi Gayrimenkul Değerleme A.Ş.",
  "D Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "Değer Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Demir Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Denge Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Detay Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "DGD Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Donatı Gayrimenkul Değerleme A.Ş.",
  "Dora Gayrimenkul Değerleme A.Ş.",
  "Dönüşüm Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Dünya Grup Gayrimenkul Değerleme Danışmanlık A.Ş.",
  "Düzey Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Ege Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "Ekip Taşınmaz Değerleme A.Ş.",
  "Ekol Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Eksen Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Eksper Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Ekspertur Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Elit Gayrimenkul Değerleme A.Ş.",
  "Elma Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Emek Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "Emsal Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Epos Gayrimenkul Danışmanlık ve Değerleme A.Ş.",
  "Etik Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Etkin Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Eva Gayrimenkul Değerleme Danışmanlık A.Ş.",
  "Focus Global Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Form Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Galata Taşınmaz Değerleme ve Danışmanlık Hizmetleri A.Ş.",
  "GEDAŞ Gayrimenkul Değerleme A.Ş.",
  "Gerçek Gayrimenkul Değerleme A.Ş.",
  "Girişim Gayrimenkul Değerleme A.Ş.",
  "Gold Gayrimenkul Değerleme Ekspertiz ve Danışmanlık A.Ş.",
  "Gordion Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "Harmoni Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "İdeal Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "İlke Gayrimenkul Değerleme A.Ş.",
  "İnternorm Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "İnvest Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "İstanbul Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "İstem Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Kalme Kurumsal Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Karat Taşınmaz Değerleme A.Ş.",
  "Kare Gayrimenkul Değerleme A.Ş.",
  "Karşıyaka Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Kent Kurumsal Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "KFB Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Koza Gayrimenkul Değerleme A.Ş.",
  "Makro Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Mavi Gayrimenkul Değerleme A.Ş.",
  "Metrik Gayrimenkul Değerleme Danışmanlık A.Ş.",
  "Metropol Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Mülk Kurumsal Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Net Kurumsal Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Nokta Taşınmaz Değerleme A.Ş.",
  "Nova Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "ODE Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Özen Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "Öztürk Gayrimenkul Değerleme A.Ş.",
  "Piramit Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Platform Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Prime Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Rasyonel Grup Taşınmaz Değerleme A.Ş.",
  "Reel Gayrimenkul Değerleme A.Ş.",
  "Referans Grup Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Rehber Gayrimenkul Değerleme Danışmanlık A.Ş.",
  "RM Ritim Gayrimenkul Değerleme A.Ş.",
  "Rota Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "SEAK Gayrimenkul Değerleme A.Ş.",
  "Sentez Gayrimenkul Değerleme A.Ş.",
  "Smart Kurumsal Gayrimenkul Değerleme ve Danışmanlık Hizmetleri A.Ş.",
  "SOM Kurumsal Gayrimenkul Değerleme ve Danışmanlık Hizmetleri Ticaret A.Ş.",
  "Sümer Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Tadem Taşınmaz Değerleme Müşavirlik A.Ş.",
  "Taksim Kurumsal Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Talya Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Teknik Gayrimenkul Değerleme A.Ş.",
  "Terra Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "TSKB Gayrimenkul Değerleme A.Ş.",
  "Tuveo Kurumsal Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Ulusal Gayrimenkul Değerleme A.Ş.",
  "Uzman Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Vakıf Gayrimenkul Değerleme A.Ş.",
  "Varlık Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "Vera Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Vizyon Taşınmaz Değerleme ve Danışmanlık A.Ş.",
  "Yatırım Gayrimenkul Değerleme A.Ş.",
  "Yeditepe Grup Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Yetkin Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Zeugma Gayrimenkul Değerleme ve Danışmanlık A.Ş.",
  "Zirve Gayrimenkul Değerleme A.Ş.",
] as const;
